version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: contacts_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "465:465"
      - "587:587"
      - "25:25"
    volumes:
      - .:/app

volumes:
  postgres_data:
